services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: abduvoris-content-hub-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - content-hub-abduvoris
    db:
        image: postgres:15
        container_name: abduvoris-content-hub-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5435:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - content-hub-abduvoris

    nginx:
        image: nginx:alpine
        container_name: abduvoris-content-hub-nginx
        ports:
            - "88:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - content-hub-abduvoris

volumes:
    pgdata:

networks:
    content-hub-abduvoris:
