services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: content-hub-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - content-hub
    node:
        image: node:18
        container_name: content-hub-node
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: sh -c "npm install && npm run dev"
        networks:
            - content-hub
        ports:
            - "5173:5173" # Vite server uchun
        environment:
            - HOST=0.0.0.0
    db:
        image: postgres:15
        container_name: content-hub-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5435:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - content-hub

    nginx:
        image: nginx:alpine
        container_name: content-hub-nginx
        ports:
            - "88:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - content-hub

volumes:
    pgdata:

networks:
    content-hub:
